
# Abstract

White matter hyperintensities (WMHs) are foci of abnormal signal
intensity in white matter regions seen with magnetic resonance imaging
(MRI). WMHs are associated with normal aging and have shown prognostic
value in neurological conditions such as traumatic brain injury (TBI).
The impracticality of manually quantifying these lesions limits their
clinical utility and motivates the utilization of machine learning
techniques for automated segmentation workflows.  Herein, we develop a
concatenated random forest framework with image features for
segmenting WMHs in a TBI cohort. The framework is built upon the
Advanced Normalization Tools (ANTs)  and ANTsR toolkits.  MR
(3D FLAIR, T2-, and T1-weighted) images from 24 service members and
veterans scanned in the Chronic Effects of Neurotrauma Consortium’s
(CENC) observational study were acquired. Manual annotations were
employed for both training and evaluation using a leave-one-out
strategy.  \textcolor{black}{Performance measures include sensitivity,
positive predictive value, $F_1$ score, and relative volume difference.
Final average results were: sensitivity = 0.68 $\pm$ 0.38, positive
predictive value = 0.51 $\pm$ 0.40, $F_1$ = 0.52 $\pm$ 0.36,
relative volume difference} = 43 $\pm$ 26\%.  In addition, three
lesion size ranges are selected to illustrate the variation in
performance with lesion size.}  Paired with
correlative outcome data, supervised learning methods may allow for
identification of imaging features predictive of diagnosis and prognosis
in individual TBI patients.

\clearpage
