
# Discussion

<!-- Nick could you add some detail here on how this technique compares
to other automated or semi automated approaches for WMH detection? -->


\textcolor{blue}{
In evaluating the segmentation results, there are limited methodologies described in the
literature for automatic segmentation of WMHs despite the numerous clinical studies}
[@Debette:2010aa;@Kloppenborg:2014aa] \textcolor{blue}{exploring the connections between WMHs and TBI.
However, we can extrapolate from similar application areas where such methodologies have a
much longer history of development such as white matter lesion segmentation in
multiple sclerosis )MS).  In a recent review [@Garcia-Lorenzo:2013aa], 47 total papers
were found during a literature search and evaluated which concern automated segmentation of white
matter lesions in MS.  The most widely-used data for algorithmic evaluation consists
of two cohorts from two different sites used in
the MS Lesion segmentation challenge associated with the international MICCAI 2008
conference.  For comparison, this challenge training data set
has a mean lesion load of 204 ($\pm$ 752) mm$^3$ per lesion (compared with
our mean lesion load of 33.8 ($\pm$ 55.4) voxels $\times$ 1.2 mm$^3$ per voxel =
40.56 ($\pm$ 66.48) mm$^3$ per lesion) and the resolution is
almost twice what is used in this study (i.e., 0.5 $\times$ 0.5 $\times$ 0.5).
Note that our relative volume difference numbers are comparable to the
relative volume difference {\em between raters} of 68 percent (cf Figure 5 (d))}
[@vanginneken:2007aa].


Regarding the feature rankings, it is interesting to note some of the other top performing features for Stage 1.
The contralateral difference FLAIR image is  highly discriminative over the set of
evaluation random forest models (see Figure 8).  This accords with the known clinical relevance of
FLAIR images for identifying white matter hyperintensities and the fact that such
pathology does not typically manifest symmetrically in both hemispheres.  Interestingly, the
posterior maps for the deep gray matter are extremely important for accurate white matter
hyperintensity segmentation.  Perhaps the spatial specification of deep
gray matter aids in the removal of false positives.  Inspection of the bottom of the
plots demonstrates the lack of discriminating features associated with the
T1 image which is also well-known in the clinical literature.

![(a) FLAIR image slice illustrating WMHs which have been manually delineated.
The region around the WMHs is enlarged (b) in the original FLAIR and the
(c) contralateral FLAIR difference image.](Figures/FLAIRcontralaleteralWithLesionsAlternate.png)

As described earlier, for Stage 2, we used the output random forest voting maps from Stage
1 as both features themselves and as priors for input to a Bayesian-based segmentation with
an additional MRF spatial prior.  In Figure 7, the voting maps are labeled as
"_RFStage1VotingMaps_" where the final numeral is associated with the brain
parenchymal labeling given previously.  Similarly, the additional RF prior segmentation
feature probability maps are labeled as "_RFBrainSegmentationPosteriors_".
The Stage 2 feature importance plot follows similar
trends as that for Stage 1 with the T1 images not contributing much to the identification
of white matter hyperintensity voxels.  The initial voting maps from Stage 1 are extremely
important with the top 3 being the estimated locations of the 1) gray matter, 2) white matter, and
3) white matter hyperintensities.  Since these tissue type can be conflated based on intensity
alone it is intuitive that such features would be important.






<!--

* Evaluation * Proper context * We only have manual labelings from a
single radiologist ( * TBI white matter hyperintensities are more
difficult to segment than MS lesions * individual lesions are smaller *
lesion load is typically smaller * not prone to enhancement * less
distinct from surrounding tissue ? * Despite the doubts regarding the
efficacy of a typical segmentation validation, our contribution is
useful because * the total segmentation framework is publicly available
within the ANTs/ANTsR framework * although only a single site is
analyzed, the feature images are site-agnostic * we plan to apply the
current RF models directly to the other site data * we can then build
the training database further by enlisting other experts * Is this the
first work exploring segmentation of white matter hyperintensities in
TBI? * The data (including manual tracings) will be made available as
part of the FITBIR effort.

-->

# Conclusions

The current communications describes a supervised statistical learning
methodology for identifying WHMs within multimodal MR brain imaging.
This effort utilized information acquired from the manual segmentation
of WMHs from FLAIR images to help build two-stage ensembles of decision
trees for the automated identification of these lesions. Although only a
single expert was used to produce the manual labelings, our intent is to
further refine the proposed paradigm by crowdsourcing with feedback from
other experts who interact with both the data and methodology.  Also, we
recognize that only a single site was used for evaluating the proposed
framework.  However, we are currently processing other site data with
the models developed for this work and the results look promising since
the developed features are site-agnostic.

As far as we know, this is the first report utilizing a novel random
forest approach to identify WMHs in a cohort of TBI patients.  TBI WMHs
tend to be more difficult to segment than MS lesions as the former tend
to be smaller with an overall smaller lesion load.  Also, enhancement
protocols with the former tend to be less successful than with the
latter.  As mentioned previously, the work in MS lesion segmentation is
extensive with a handful of techniques being publicly available.

<!--
Our
framework is also available as open-source as part of well-known
neuroimaging tools which easily allows for additions/extensions but is
also, as far as we know, the first random forest-based technique
available for such application.
-->

Two major meta-analyses of WMHs have been published covering the periods
prior to [@Debette:2010aa] and after 2010 [@Kloppenborg:2014aa].
Debette & Markus [@Debette:2010aa] found that the presence of
WMHs was related to subsequent cognitive decline, a higher risk of
developing dementia, stroke, and of mortality. Lesion volume at baseline
was also predictive of cognitive decline. Kloppenborg et al.
[@Kloppenborg:2014aa] of 23 cross-sectional studies reporting MRI and
concurrent neuropsychological results in patients with heterogeneous
diagnoses but without previously diagnosed cognitive impairment, found
that WMHs were associated with cognitive deficit (effect size of -0.10,
95% CI: -0.13 to -0.08) after controlling for age.


Despite the potential clinical significance of WMHs
these lesions receive little
attention in current clinical workflows. When reported in a standard
neuroradiologist interpretation, they are typically handled as
incidental findings and are assigned little clinical significance. This
likely reflects the impracticality of performing a detailed assessment
of number, volume, and distribution within a qualitative
neuroradiologist interpretation as well as the lack of correlative
information on how the presence and distribution of these lesions may
inform a diagnosis and prognosis in the appropriate clinical setting. To
date, automated or semi-automated tools for the detection of WMHs have
lacked the specificity and efficiency for the mining of large-scale
datasets to generate highly granular data on whether these lesions
possess any true diagnostic or prognostic value in the setting of a
specific disease process. The present communication describes a
supervised statistical learning tool that is appropriate for the
application to such large-scale datasets.

<!--

The currently described tool is just one example of how "supervised
learning" algorithms might be applied to aid in the diagnosis of TBI and
other disease processes through the specific identification of features
predictive of a given disease state. It is an important demonstration of
the potential power of these analytical approaches in the rapid but
comprehensive mining of information from neuroimaging examinations.
Supervised learning algorithms are presently employed across a wide
variety of settings for the rapid identification of predictive imaging
features [@Plis:2014aa;@Suk:2015aa;@Li:2014aa;@Liu:2015aa]. Automobile
manufacturers utilize these types of approaches to equip self-driving
vehicles to recognize and respond to unique external surroundings
through the identification of visual information sufficiently similar to
previously assimilated training data [@HadsellSBESKML09;@FarabetCNL12].
Similarly, in the context of the neuroimaging assessments, deep learning
approaches may allow for the rapid identification of information
predictive of disease state in an individual patient. These approaches
have been applied to the segmentation of macroscopically visible
structures [@Plis:2014aa;@Suk:2015aa;@Li:2014aa;@Liu:2015aa].
Additionally, these approaches might be applied to the interrogation of
imaging data in the individual patient with a primary quantitative
output metrics to include sequences such as diffusion tensor imaging
(DTI) and its variants, functional connectivity, perfusion weighted
imaging, and cortical thickness assessments. At present, these advanced
neuroimaging sequences are confined to cohort-based research studies due
to the lack of available analytical tools to assess the information in
the setting of the individual patient [@Mayer:2014aa]. Application of
deep learning approaches in the context of data with primary
quantitative outputs will require large scale normative and disease
specific databases. Building these large scale imaging libraries is
resource intensive and requires a multi-center approach with harmonized
scanners between sites and correlative non-imaging clinical data. Large
scale TBI data is becoming increasingly available through activities
such as the Chronic Effects of Neurotrauma Consortium (CENC),
Transforming Research and Clinical Knowledge in TBI (TRACK-TBI),
Collaborative European Neurotrauma Effectiveness Research in TBI
(CENTER-TBI), Department of Defense Alzheimer’s Disease Neuroimaging
Initiative (DOD-ADNI), and other data being consolidated through FITBIR.
In concert with any available high quality normative neuroimaging data,
deep learning algorithms may be well positioned to help transform how
neuroimaging is interpreted for the clinical management of patients with
this disease process.

-->

\clearpage
