
# Introduction

## White matter hyperintensities in TBI

\textcolor{black}{White matter hyperintensities (WMHs) are foci of abnormally increased signal intensity seen within white matter regions within the cerebrum and brainstem on fluid attenuation inversion recovery (FLAIR) magnetic resonance imaging (MRI) sequences.
WMHs are a frequent finding following traumatic brain injury (TBI) and have been correlated with functional outcome and injury severity in both pediatric} [@Bigler:2013aa;@Smitherman:2016aa] \textcolor{black}{and adult} [@Marquez-de-la-Plata:2007aa;@Moen:2014aa;@Ding:2008aa;@Pierallini:2000aa] \textcolor{black}{populations.}

\textcolor{black}{Further research involving WMHs has shown that regional distribution and volume of WMHs have been shown to possess prognostic value in the TBI patient} [@Pierallini:2000aa;@Weiss:2008aa;@Smitherman:2016aa;@Levin:1988aa]\textcolor{black}{. Specifically, lesion volume in corpus callosum correlates with functional scores in the acute phase following injury, while lesion volume in frontal lobes correlates with scores at 1 year following injury} [@Pierallini:2000aa]\textcolor{black}{.
Further, volume of FLAIR lesions within the corpus
callosum, brainstem, and thalamus in patients with severe TBI correlates
with Glasgow Outcome-Extended (GOS-E) scores---a numeric groupwise assessment used to
classify ``outcome'' in TBI patients where ``outcome'' refers to the
spectrum of possible prognoses from death to disability to recovery} [@Moen:2014aa]\textcolor{black}{. Additionally,
in patients who are comatose following severe TBI
the regional distribution of FLAIR lesions within the pons, midbrain, hypothalamus, basal forebrain, parietal, temporal, occipital lobes, and insula along with the observation of grasping or chewing behavior are associated with poor outcome} [@Weiss:2008aa].

\textcolor{black}{Despite the above findings which demonstrate that WMHs have potential prognostic value, they are not routinely employed as a diagnostic measure in clinical practice.  Performing a comprehensive manual counting of number and distribution of lesions in the clinical setting is simply not practical. The development of such lesion quantification approaches may allow for the practical inclusion of this type of information within routine radiological practice.  In this work, we present an automated framework for quantification of WMHs in
multi-modal MRI using the random forest machine learning technique.}


## Random forests for WMH segmentation

<!--
Machine learning and pattern recognition techniques have seen increased application
for various medical image analysis workflows (see, for example, the annual
Workshop on Machine Learning in Medical Imaging held in conjunction with the Medical
Image Computing and Computer-Aided Intervention (MICCAI) international meeting).
Popular techniques such as support vector machines and neural networks have been applied
successfully to clinically relevant imaging tasks such as supervised image segmentation
(e.g., [@Bauer:2011aa]) and diagnostic prediction (e.g., [@Tong:2014aa;@Liu:2013aa]).
Facilitating the current employment of such techniques are the number of available imaging
data sets [@Van-Horn:2014aa] and the public availability of data science packages such as
SciPy [@scipy] and the R project for statistical computing [@R] and their associated
extensions.
-->

The random forests framework [@breiman2001] is a popular machine learning technique that has demonstrated significant utility for supervised segmentation tasks (e.g.,
normal human brain segmentation [@yi2009]) and other computer vision applications
[@viola2005].
\textcolor{black}{Random forest-based paradigms have been successfully employed in the
delineation of other neuropathologies} [@geremia2011;@Pustina:2016aa;@geremia2012;@bauer2012;@zikic2012;@Tustison:2015aa]
\textcolor{black}{for both single and multi-modal acquisition protocols.}

<!--
Of note, these
latter random forest approaches for brain tumor segmentation have performed well in recent
international competitions established in response to the lack of objective comparisons between segmentation algorithms (i.e.,  the Multimodal Brain Tumor Segmentation (BRATS) challenge was initiated in 2012 [@Menze:2015aa].
-->

Random forests are conceptually straightforward [@breiman2001].
\textcolor{black}{The basic component of
the random forest paradigm is the ``decision tree'' often represented by a flowchart or
graph where internal nodes represent ``tests'', or decisions, and the edges represent the outcome of those tests.  The final, or end, nodes represent the various classifications produced by traversal through the decision tree.  For the proposed application, individual
voxels (and their corresponding feature values) are introduced at the root of a particular
decision tree and traverse the edges and internal nodes ultimately ending up at one of
the classification nodes according to the tests at each internal node.  A single random
forest model will consist of many such trees (often refered to as an ``ensemble'').}
\textcolor{black}{Although decision trees had been extensively studied, the success of employing collections of such weak learners for boosting machine learning performance
(e.g., AdaBoost)} [@schapire1990;@freund1997]
\textcolor{black}{influenced the similarly styled conglomeration of decision trees into ``forests'' with randomized node optimization} [@ho1995;@amit1997].
\textcolor{black}{Finally, Breiman} [@breiman2001]
\textcolor{black}{improved accuracy by random sampling of training data (i.e., ``bagging'') resulting
in the current random forest technique applied here.}
\textcolor{black}{As voxels and their feature values are ``pushed'' through each decision tree in the forest,  votes for each label are accumulated and converted to probability values for all classification possiblilities at
each voxel location.}

In this work, we develop a concatenated random forest framework with a
feature image set (both spatial and intensity-based)
for segmenting WMHs in a large TBI cohort.
The entire framework is built on the well-known open-source
Advanced Normalization Tools (ANTs)[^i1] and ANTsR[^i2] toolkits.
Further motivating this research is the availability of several large publicly available  imaging data sets that permits testing reproducibility of this automated routine for WMH segmentation and quantification.

[^i1]: https://github.com/stnava/ANTs
[^i2]: https://github.com/stnava/ANTsR
